//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: HealthEnclave.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate HealthEnclave_HealthEnclaveClient, then call methods of this protocol to make API calls.
public protocol HealthEnclave_HealthEnclaveClientProtocol {
  func documentRequests(callOptions: CallOptions?, handler: @escaping (HealthEnclave_DocumentIdentifier) -> Void) -> BidirectionalStreamingCall<HealthEnclave_DocumentIdentifier, HealthEnclave_DocumentIdentifier>
  func documentRequests2(callOptions: CallOptions?, handler: @escaping (HealthEnclave_DocumentIdentifier) -> Void) -> BidirectionalStreamingCall<HealthEnclave_DocumentIdentifier, HealthEnclave_DocumentIdentifier>
}

public final class HealthEnclave_HealthEnclaveClient: GRPCClient, HealthEnclave_HealthEnclaveClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the health_enclave.HealthEnclave service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// The client sends a stream of document identifiers to the server.
  /// The server shall delete local documents not contained in the clients stream.
  /// The server shall respond with a stream of document identifiers that are locally not present.
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func documentRequests(callOptions: CallOptions? = nil, handler: @escaping (HealthEnclave_DocumentIdentifier) -> Void) -> BidirectionalStreamingCall<HealthEnclave_DocumentIdentifier, HealthEnclave_DocumentIdentifier> {
    return self.makeBidirectionalStreamingCall(path: "/health_enclave.HealthEnclave/DocumentRequests",
                                               callOptions: callOptions ?? self.defaultCallOptions,
                                               handler: handler)
  }

  /// Bidirectional streaming call to DocumentRequests2
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func documentRequests2(callOptions: CallOptions? = nil, handler: @escaping (HealthEnclave_DocumentIdentifier) -> Void) -> BidirectionalStreamingCall<HealthEnclave_DocumentIdentifier, HealthEnclave_DocumentIdentifier> {
    return self.makeBidirectionalStreamingCall(path: "/health_enclave.HealthEnclave/DocumentRequests2",
                                               callOptions: callOptions ?? self.defaultCallOptions,
                                               handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol HealthEnclave_HealthEnclaveProvider: CallHandlerProvider {
  /// The client sends a stream of document identifiers to the server.
  /// The server shall delete local documents not contained in the clients stream.
  /// The server shall respond with a stream of document identifiers that are locally not present.
  func documentRequests(context: StreamingResponseCallContext<HealthEnclave_DocumentIdentifier>) -> EventLoopFuture<(StreamEvent<HealthEnclave_DocumentIdentifier>) -> Void>
  func documentRequests2(context: StreamingResponseCallContext<HealthEnclave_DocumentIdentifier>) -> EventLoopFuture<(StreamEvent<HealthEnclave_DocumentIdentifier>) -> Void>
}

extension HealthEnclave_HealthEnclaveProvider {
  public var serviceName: String { return "health_enclave.HealthEnclave" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "DocumentRequests":
      return BidirectionalStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.documentRequests(context: context)
      }

    case "DocumentRequests2":
      return BidirectionalStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.documentRequests2(context: context)
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload` for request and response messages
extension HealthEnclave_DocumentIdentifier: GRPCProtobufPayload {}

